services:
  web: # Menjalankan container Next.js untuk aplikasi inventory
    container_name: nextjs-inv-app
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    restart: always
    environment:
      - NODE_ENV=development
    command: npm run docker:dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env
    # depends_on:
    #   - db
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "http"
      # Ganti nextjs-inv-app jika nama service Next.js Anda berbeda di file ini
      - "nextjs-inv-app:3000" 
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040" # Port untuk melihat dashboard Ngrok secara lokal
    depends_on:
      - web
#   db: # Membuat container database postgres untuk menyimpan data inventory
#     container_name: nextjs-inv-db
#     image: postgres:18.4-alpine
#     restart: always
#     environment:
#       POSTGRES_DB: $POSTGRES_DB
#       POSTGRES_USER: $POSTGRES_USER
#       POSTGRES_PASSWORD: $POSTGRES_PASSWORD
#     ports:
#       - "5432:5432"
#     expose:
#       - "5432"
#     volumes:
#       - db_data:/var/lib/postgresql/data
# volumes:
#   db_data: